WITH RECURSIVE TIMETABLE(HOUR) AS (
        SELECT 0
    UNION
        SELECT T.HOUR + 1 
        FROM TIMETABLE T
        WHERE T.HOUR < 23
)

SELECT HOUR, COUNT(A.ANIMAL_ID)
FROM TIMETABLE T 
    LEFT JOIN ANIMAL_OUTS A 
    ON T.HOUR = HOUR(A.DATETIME)
GROUP BY HOUR
ORDER BY HOUR
